transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/components.v}
vlog -vlog01compat -work work +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/DE1_SoC_Computer.v}
vlog -vlog01compat -work work +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/hex_decoder.v}
vlog -vlog01compat -work work +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/db {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/db/mult_i5n.v}
vlib Computer_System
vmap Computer_System Computer_System
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/Computer_System.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_2.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_002.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_pio_x.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Pixel_RGB_Resampler.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Pixel_FIFO.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Pixel_DMA.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_PLL.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_PLL_video_pll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Dual_Clock_FIFO.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_avalon_video_vga_timing.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_video_128_character_rom.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Char_Buffer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_video_alpha_blender_normal.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_VGA_Subsystem_VGA_Alpha_Blender.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL_sys_pll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_SDRAM.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_avalon_video_dma_ctrl_addr_trans.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_Onchip_SRAM.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_av_config_serial_bus_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_slow_clock_generator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_av_config_auto_init.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_av_config_auto_init_ob_de1_soc.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_av_config_auto_init_ob_audio.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_up_av_config_auto_init_ob_adv7180.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_AV_Config.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_irq_mapper.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_002_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_rsp_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_router_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_router.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_005.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_004.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_003.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io_border.sv}
vlog -sv -work Computer_System +incdir+C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules {C:/Users/hh543/Documents/lab1/computer_640_16bit_video/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_fpga_interfaces.sv}

